// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwvNeaPOybKkgNMrWB4fVKeSID-8SF9lA',
    appId: '1:298079047994:web:e3c3c7ee7baea57e27c003',
    messagingSenderId: '298079047994',
    projectId: 'clipza-1bf99',
    authDomain: 'clipza-1bf99.firebaseapp.com',
    storageBucket: 'clipza-1bf99.firebasestorage.app',
    measurementId: 'G-1GLS3EKZKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ5JgrOAPRzKpRNbu8jJgNQ2MMZztDXso',
    appId: '1:298079047994:android:83875eed4257234827c003',
    messagingSenderId: '298079047994',
    projectId: 'clipza-1bf99',
    storageBucket: 'clipza-1bf99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFbzsGaJKazqgNNdIpUpwWdYVvYOcjLMg',
    appId: '1:298079047994:ios:682ab266917135e527c003',
    messagingSenderId: '298079047994',
    projectId: 'clipza-1bf99',
    storageBucket: 'clipza-1bf99.firebasestorage.app',
    iosClientId: '298079047994-s7ott29m7hcars84kljc7o5jeju8kac0.apps.googleusercontent.com',
    iosBundleId: 'com.example.clipza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFbzsGaJKazqgNNdIpUpwWdYVvYOcjLMg',
    appId: '1:298079047994:ios:682ab266917135e527c003',
    messagingSenderId: '298079047994',
    projectId: 'clipza-1bf99',
    storageBucket: 'clipza-1bf99.firebasestorage.app',
    iosClientId: '298079047994-s7ott29m7hcars84kljc7o5jeju8kac0.apps.googleusercontent.com',
    iosBundleId: 'com.example.clipza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwvNeaPOybKkgNMrWB4fVKeSID-8SF9lA',
    appId: '1:298079047994:web:899f1bcc42e27e7227c003',
    messagingSenderId: '298079047994',
    projectId: 'clipza-1bf99',
    authDomain: 'clipza-1bf99.firebaseapp.com',
    storageBucket: 'clipza-1bf99.firebasestorage.app',
    measurementId: 'G-8P2B5F66SD',
  );
}
